add resources
uclaacm/membership-portal pull request #40
Opened 2021-05-17 08:58 UTC by lumisphere902

Handle resources when adding/fetching events.

One weird thing: all the current databases have both an auto inc ID as the primary key, as well as a UUID. It seems to me like the UUID should be the primary key, as I don't think the auto inc ID is used anywhere. However, I followed this pattern just in case I'm missing something.

2021-05-17 09:19 UTC, mattxwang requested changes
Very cursory review, but we can talk about it more @ dev team meeting!

2021-05-17 09:19 UTC, mattxwang commented on app/db/schema/resource.js
> +          args: [3, 255],
Can we make this max length longer? See https://github.com/uclaacm/membership-portal-ui/issues/81

2021-05-17 09:19 UTC, mattxwang commented on app/util/resource_utils.js
> +const populateEventsWithResources = (events) => {
Is there a way we'd have this call `populateOneEventWithResources`? seems like a reasonable-ish way to de-duplicate logic

2021-05-17 09:19 UTC, mattxwang commented on app/db/schema/resource.js
> +    // resource type
i'm a bit out of the loop, is the plan for `type` to be a free-floating string, or for it to be an enum?

(if it's the former, we probably want to enforce a length min/max)

2021-05-17 09:19 UTC, mattxwang commented on app/db/schema/resource.js
> +    // resource value
Will resource ever not be a link? If so, we may want to validate the link-ness!

2021-05-17 09:20 UTC, mattxwang commented
> One weird thing: all the current databases have both an auto inc ID as the primary key, as well as a UUID. It seems to me like the UUID should be the primary key, as I don't think the auto inc ID is used anywhere. However, I followed this pattern just in case I'm missing something.

Extremely strange, though also I imagine reformatting might be a bit of a nightmare. Let's follow up with this in another issue, warrants investigation.

2021-05-17 09:37 UTC, lumisphere902 commented on app/db/schema/resource.js
> +          args: [3, 255],
OK, it's just 255 because the String type is varchar(255). What's a reasonable max length? 1000?

2022-07-12 22:09 UTC, lumisphere902 commented
Closing due to inactivity

2022-07-12 22:09 UTC, closed without merging